spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/student
    username: postgres
    password: postgres
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
security.basic.enabled: false

